version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: IRIS
    ports:
      - 52773
      - 53773
    volumes:
      - ./:/irisdev/app
