version: '3'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - dev_volume:/home/project/shared/Samples-PEX-Course

    ports:
      - 52773:52773
      - 51773:51773
  IDE:
    image: linuxserver/code-server  
    ports: 
      - 8443:8443
    volumes:
      - dev_volume:/home/project/shared/Samples-PEX-Course


volumes: 
  dev_volume: