version: '3'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 52773:52773
      - 51773:51773
    volumes:
      - ./Java/src:/home/project/shared/Samples-PEX-Course/Java/src 
      - ./DotNet/Finance:/home/project/shared/Samples-PEX-Course/DotNet/Finance
      - ./data/:/home/project/shared/Samples-PEX-Course/data
  

volumes: 
  dev_volume: