version: '3'
services:
  iris:
    build: .
    environment:
      - CLASSPATH=/datavol/PEX/bin/*:/datavol/PEX/Java/bin

    ports:
      - "52773:52773"
      - "51773:51773"
    volumes:
      - "./:/datavol"
    
