Class Demo.PEX.Production.NonPollingBusinessService Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="Demo.PEX.Production.NonPollingBusinessService" LogGeneralTraceEvents="false">
<Description></Description>
<ActorPoolSize>2</ActorPoolSize>
<Item Name="Demo.PEX.NonPollingBusinessService" Category="" ClassName="Demo.PEX.NonPollingBusinessService" PoolSize="1" Enabled="true" Foreground="true" Comment="" LogTraceEvents="false" Schedule="">
</Item>
</Production>
}

}
